const VL_CONFIG={videosPorLote:21,videosJsonPath:'/videos.json'};let vlTodosOsVideos=[];let vlVideosCarregados=0;let vlEstaCarregando=!1;let vlObserver=null;let vlVideoIdAtual=null;let vlModal=null;let vlIframe=null;document.addEventListener('DOMContentLoaded',function(){const grid=document.getElementById('vl-grid');if(grid){carregarVideosVl()}
initThemeToggle();initDraggableTheme();initTranslateWidget();initDraggableTranslate();initMobileMenu();initBackToTopVl();initClickOutsideVl();initEscapeKeyVl()});async function carregarVideosVl(){const grid=document.getElementById('vl-grid');if(!grid)return;try{let data=null;try{const cache=await caches.open('vitaotub-cache-v3.1-20260804');const cachedResponse=await cache.match(VL_CONFIG.videosJsonPath);if(cachedResponse){data=await cachedResponse.json()}}catch(e){}
if(!data){const response=await fetch(VL_CONFIG.videosJsonPath);if(!response.ok)throw new Error('Erro ao carregar vídeos');data=await response.json()}
vlTodosOsVideos=data.videos;if(!vlTodosOsVideos||vlTodosOsVideos.length===0){grid.innerHTML='<p class="vl-placeholder">Nenhum vídeo encontrado.</p>';return}
vlVideosCarregados=0;grid.innerHTML='';vlEstaCarregando=!1;if(vlObserver){vlObserver.disconnect();vlObserver=null}
carregarProximosVideosVl();configurarScrollInfinitoVl()}catch(error){console.error('Erro ao carregar vídeos:',error);grid.innerHTML='<p class="vl-placeholder" style="color: #ff5555;">Erro ao carregar vídeos. Tente novamente mais tarde.</p>'}}
function carregarProximosVideosVl(){const grid=document.getElementById('vl-grid');if(!grid){console.error('❌ Container não encontrado!');return}
console.log('📊 Status atual (Vídeos & Lives):');console.log('  - Vídeos carregados:',vlVideosCarregados);console.log('  - Total de vídeos:',vlTodosOsVideos.length);if(vlVideosCarregados>=vlTodosOsVideos.length){console.log('🎉 Todos os vídeos já foram carregados!');const sentinela=document.getElementById('vl-sentinel');if(sentinela){sentinela.textContent='🎉 Todos os vídeos carregados!';sentinela.className='done'}
return}
if(vlEstaCarregando){console.log('⏳ Já está carregando...');return}
vlEstaCarregando=!0;console.log('🔄 Iniciando carregamento do lote...');const proximos=vlTodosOsVideos.slice(vlVideosCarregados,vlVideosCarregados+VL_CONFIG.videosPorLote);console.log('📦 Lote atual:',proximos.length,'vídeos (',vlVideosCarregados,'a',vlVideosCarregados+proximos.length-1,')');proximos.forEach((video,index)=>{console.log(`  ➕ Adicionando vídeo ${vlVideosCarregados + index + 1}: ${video.title}`);const card=criarCardVl(video);grid.appendChild(card)});vlVideosCarregados+=proximos.length;console.log('✅ Lote carregado! Total:',vlVideosCarregados,'de',vlTodosOsVideos.length);vlEstaCarregando=!1;const sentinela=document.getElementById('vl-sentinel');if(sentinela){grid.appendChild(sentinela);if(vlVideosCarregados<vlTodosOsVideos.length){sentinela.textContent='🔄 Carregando mais vídeos...';sentinela.className='loading'}else{sentinela.textContent='🎉 Todos os vídeos carregados!';sentinela.className='done'}
console.log('📌 Sentinela movido para o final.')}
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')}
function criarCardVl(video){const videoId=video.id;const titulo=video.title||'Vídeo sem título';const dataPub=video.date||new Date().toLocaleDateString('pt-BR');const thumbnailUrl=`https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`;const card=document.createElement('article');card.className='vl-card';card.setAttribute('data-video-id',videoId);card.innerHTML=`
        <div class="vl-thumbnail" onclick="abrirModalVl('${videoId}')" role="button" tabindex="0" aria-label="Assistir: ${escapeHtmlVl(titulo)}">
            <img src="${thumbnailUrl}" alt="${escapeHtmlVl(titulo)}" loading="lazy" onerror="this.src='https://img.youtube.com/vi/${videoId}/hqdefault.jpg'">
            <div class="vl-play-icon"><i class="fa-solid fa-circle-play"></i></div>
        </div>
        <div class="vl-content">
            <h3 class="vl-title">${escapeHtmlVl(titulo)}</h3>
            <div class="vl-meta-actions">
                <div class="vl-meta-left">
                    <span class="vl-date">📅 ${escapeHtmlVl(dataPub)}</span>
                    <span class="vl-author">✍️ VitãoTub</span>
                </div>
                <div class="vl-actions-right">
                    <button class="vl-btn-share" onclick="event.stopPropagation(); compartilharVideoVl('${videoId}')" title="Compartilhar vídeo" aria-label="Compartilhar vídeo">
                        <i class="fa-solid fa-share-nodes"></i>
                    </button>
                    <a href="https://www.youtube.com/watch?v=${videoId}" target="_blank" rel="noopener" class="vl-btn-youtube" onclick="event.stopPropagation();" title="Assistir no YouTube" aria-label="Assistir no YouTube">
                        <i class="fa-brands fa-youtube"></i>
                    </a>
                </div>
            </div>
        </div>
    `;return card}
function escapeHtmlVl(text){if(!text)return'';return String(text).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function configurarScrollInfinitoVl(){const grid=document.getElementById('vl-grid');if(!grid){console.error('❌ Container não encontrado!');return}
const sentinelaAntigo=document.getElementById('vl-sentinel');if(sentinelaAntigo){sentinelaAntigo.remove();console.log('🧹 Sentinela antigo removido.')}
if(vlObserver){vlObserver.disconnect();vlObserver=null;console.log('🧹 Observer antigo desconectado.')}
const sentinela=document.createElement('div');sentinela.id='vl-sentinel';sentinela.style.height='50px';sentinela.style.width='100%';sentinela.style.display='flex';sentinela.style.justifyContent='center';sentinela.style.alignItems='center';sentinela.style.color='var(--text-dim)';sentinela.style.fontSize='0.9rem';sentinela.style.padding='30px 0';sentinela.style.backgroundColor='rgba(139, 92, 246, 0.05)';sentinela.style.borderRadius='8px';sentinela.style.marginTop='10px';sentinela.textContent='🔄 Carregando mais vídeos...';sentinela.className='loading';grid.appendChild(sentinela);console.log('✅ Sentinela criado e adicionado ao final do container.');setTimeout(()=>{const rect=sentinela.getBoundingClientRect();console.log('📍 Posição do sentinela:',rect.top,rect.bottom);console.log('📐 Altura da janela:',window.innerHeight);console.log('👀 Visível?',rect.top<window.innerHeight&&rect.bottom>0)},100);vlObserver=new IntersectionObserver((entries)=>{entries.forEach(entry=>{console.log('🔍 Sentinela detectado:',entry.isIntersecting?'VISÍVEL ✅':'OCULTO ❌');if(entry.isIntersecting&&!vlEstaCarregando&&vlVideosCarregados<vlTodosOsVideos.length){console.log('🔄 Carregando mais vídeos... (sentinela visível)');setTimeout(()=>{carregarProximosVideosVl()},100)}})},{root:null,rootMargin:'0px 0px 300px 0px',threshold:0.01});vlObserver.observe(sentinela);console.log('✅ Observer configurado e observando o sentinela.')}
function abrirModalVl(videoId){vlVideoIdAtual=videoId;vlModal=document.getElementById('vl-modal');vlIframe=document.getElementById('vl-modal-iframe');const youtubeLink=document.getElementById('vl-modal-youtube-link');if(!vlModal||!vlIframe)return;vlIframe.src=`https://www.youtube.com/embed/${videoId}?autoplay=1&rel=0&playsinline=1`;if(youtubeLink){youtubeLink.href=`https://www.youtube.com/watch?v=${videoId}`}
vlModal.classList.add('active');document.body.style.overflow='hidden';document.addEventListener('keydown',fecharModalVlEsc)}
function fecharModalVl(){const modal=document.getElementById('vl-modal');const iframe=document.getElementById('vl-modal-iframe');if(modal){modal.classList.remove('active');document.body.style.overflow=''}
if(iframe){iframe.src=''}
vlVideoIdAtual=null;document.removeEventListener('keydown',fecharModalVlEsc)}
function fecharModalVlEsc(e){if(e.key==='Escape'){fecharModalVl()}}
function compartilharVideoVl(videoId){const id=videoId||vlVideoIdAtual;if(!id)return;const videoUrl=`https://www.youtube.com/watch?v=${id}`;const mensagem=`🎬 Vídeo do VitãoTub: ${videoUrl}`;const isMobile=/Mobi|Android|iPhone|iPad/i.test(navigator.userAgent);if(isMobile&&navigator.share){navigator.share({title:'Vídeo do VitãoTub',text:'Confira este vídeo!',url:videoUrl}).catch((err)=>{if(err.name!=='AbortError')console.error('Erro ao compartilhar:',err);});return}
if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(mensagem).then(()=>{alert('✅ Link do vídeo copiado! Compartilhe com seus amigos.')}).catch(()=>{fallbackCopyVl(mensagem)})}else{fallbackCopyVl(mensagem)}}
function fallbackCopyVl(text){const tempInput=document.createElement('input');tempInput.value=text;tempInput.style.position='fixed';tempInput.style.opacity='0';document.body.appendChild(tempInput);tempInput.select();try{document.execCommand('copy');alert('✅ Link do vídeo copiado! Compartilhe com seus amigos.')}catch(e){alert('❌ Não foi possível copiar o link. Tente manualmente.')}
document.body.removeChild(tempInput)}
function recarregarVideosVl(){const grid=document.getElementById('vl-grid');if(!grid)return;vlTodosOsVideos=[];vlVideosCarregados=0;vlEstaCarregando=!1;if(vlObserver){vlObserver.disconnect();vlObserver=null}
grid.innerHTML='<p class="vl-placeholder">Carregando vídeos...</p>';carregarVideosVl()}
function toggleTheme(){document.body.classList.toggle('light-mode');const themeBtn=document.getElementById('theme-toggle-btn');if(document.body.classList.contains('light-mode')){localStorage.setItem('vitaotub_theme','light');if(themeBtn){themeBtn.innerHTML='🌙';themeBtn.title='Mudar para modo escuro'}}else{localStorage.setItem('vitaotub_theme','dark');if(themeBtn){themeBtn.innerHTML='☀️';themeBtn.title='Mudar para modo claro'}}}
function initThemeToggle(){const themeBtn=document.getElementById('theme-toggle-btn');if(!themeBtn)return;const savedTheme=localStorage.getItem('vitaotub_theme');if(savedTheme==='light'){document.body.classList.add('light-mode');themeBtn.innerHTML='🌙';themeBtn.title='Mudar para modo escuro'}else{themeBtn.innerHTML='☀️';themeBtn.title='Mudar para modo claro'}}
function initDraggableTheme(){const themeBtn=document.getElementById('theme-toggle-btn');if(!themeBtn){console.warn('⚠️ Botão de tema não encontrado!');return}
console.log('✅ Botão de tema encontrado!');if(localStorage.getItem('vitaotub_theme_hidden')){themeBtn.style.display='none';return}
let isDragging=!1;let hasDragged=!1;let startX,startY,startTop,startRight;let dragTimeout=null;themeBtn.addEventListener('mousedown',(e)=>{isDragging=!0;hasDragged=!1;startX=e.clientX;startY=e.clientY;const rect=themeBtn.getBoundingClientRect();startTop=rect.top;startRight=window.innerWidth-rect.right;themeBtn.style.transition='none';e.preventDefault()});themeBtn.addEventListener('touchstart',(e)=>{isDragging=!0;hasDragged=!1;startX=e.touches[0].clientX;startY=e.touches[0].clientY;const rect=themeBtn.getBoundingClientRect();startTop=rect.top;startRight=window.innerWidth-rect.right;themeBtn.style.transition='none'},{passive:!0});document.addEventListener('mousemove',(e)=>{if(!isDragging)return;hasDragged=!0;themeBtn.style.top=`${startTop + e.clientY - startY}px`;themeBtn.style.right=`${startRight - (e.clientX - startX)}px`;themeBtn.style.left='auto';themeBtn.style.bottom='auto'});document.addEventListener('touchmove',(e)=>{if(!isDragging)return;hasDragged=!0;themeBtn.style.top=`${startTop + e.touches[0].clientY - startY}px`;themeBtn.style.right=`${startRight - (e.touches[0].clientX - startX)}px`;themeBtn.style.left='auto';themeBtn.style.bottom='auto'},{passive:!0});document.addEventListener('mouseup',()=>{if(isDragging){isDragging=!1;themeBtn.style.transition='';clearTimeout(dragTimeout);dragTimeout=setTimeout(()=>{hasDragged=!1},150)}});document.addEventListener('touchend',()=>{if(isDragging){isDragging=!1;themeBtn.style.transition='';clearTimeout(dragTimeout);dragTimeout=setTimeout(()=>{hasDragged=!1},150)}});themeBtn.addEventListener('click',function(e){if(hasDragged){hasDragged=!1;return}
toggleTheme()})}
function toggleTranslateDropdown(e){if(e){e.stopPropagation();e.preventDefault()}
const dropdown=document.getElementById('translate-dropdown');if(dropdown)dropdown.classList.toggle('active');}
function translatePage(lang){if(lang==='pt'){const select=document.querySelector('.goog-te-combo');if(select){select.value='pt';select.dispatchEvent(new Event('change'));setTimeout(()=>{document.cookie='googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;';document.cookie='googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/feed/;';document.cookie='googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; domain=.vitaotub.com; path=/;';window.location.reload()},300)}else{document.cookie='googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;';document.cookie='googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/feed/;';document.cookie='googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; domain=.vitaotub.com; path=/;';window.location.reload()}
const dropdown=document.getElementById('translate-dropdown');if(dropdown)dropdown.classList.remove('active');return}
setGoogleTranslateCookieVl(lang);const checkExist=setInterval(()=>{const select=document.querySelector('.goog-te-combo');if(select){clearInterval(checkExist);select.value=lang;select.dispatchEvent(new Event('change'));const dropdown=document.getElementById('translate-dropdown');if(dropdown)dropdown.classList.remove('active');updateActiveLanguageVl(lang)}},100);setTimeout(()=>{if(!document.querySelector('.goog-te-combo'))window.location.reload();},3000)}
function setGoogleTranslateCookieVl(lang){const date=new Date();date.setTime(date.getTime()+(365*24*60*60*1000));const expires=date.toUTCString();document.cookie='googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;';document.cookie=lang==='pt'?`googtrans=/pt/pt; expires=${expires}; path=/`:`googtrans=/pt/${lang}; expires=${expires}; path=/`}
function updateActiveLanguageVl(lang){document.querySelectorAll('.translate-option').forEach(btn=>{btn.classList.remove('active-lang');if(btn.getAttribute('data-lang')===lang){btn.classList.add('active-lang')}})}
function initTranslateWidget(){const toggleBtn=document.getElementById('translate-toggle');const dropdown=document.getElementById('translate-dropdown');if(!toggleBtn||!dropdown)return;toggleBtn.removeEventListener('click',toggleTranslateDropdown);toggleBtn.addEventListener('click',toggleTranslateDropdown);setTimeout(()=>{const match=document.cookie.match(/googtrans=\/pt\/([^;]+)/);if(match&&match[1])updateActiveLanguageVl(match[1]);},1500)}
function initDraggableTranslate(){const widget=document.getElementById('translate-widget');const toggleBtn=document.getElementById('translate-toggle');if(!widget||!toggleBtn)return;if(localStorage.getItem('vitaotub_translate_hidden')){widget.style.display='none';return}
let isDragging=!1;let hasDragged=!1;let startX,startY,startLeft,startBottom;let dragTimeout=null;toggleBtn.addEventListener('mousedown',(e)=>{isDragging=!0;hasDragged=!1;startX=e.clientX;startY=e.clientY;const rect=widget.getBoundingClientRect();startLeft=rect.left;startBottom=window.innerHeight-rect.bottom;widget.style.transition='none';e.preventDefault()});toggleBtn.addEventListener('touchstart',(e)=>{isDragging=!0;hasDragged=!1;startX=e.touches[0].clientX;startY=e.touches[0].clientY;const rect=widget.getBoundingClientRect();startLeft=rect.left;startBottom=window.innerHeight-rect.bottom;widget.style.transition='none'},{passive:!0});document.addEventListener('mousemove',(e)=>{if(!isDragging)return;hasDragged=!0;widget.style.left=`${startLeft + e.clientX - startX}px`;widget.style.bottom=`${startBottom - (e.clientY - startY)}px`;widget.style.right='auto';widget.style.top='auto'});document.addEventListener('touchmove',(e)=>{if(!isDragging)return;hasDragged=!0;widget.style.left=`${startLeft + e.touches[0].clientX - startX}px`;widget.style.bottom=`${startBottom - (e.touches[0].clientY - startY)}px`;widget.style.right='auto';widget.style.top='auto'},{passive:!0});document.addEventListener('mouseup',()=>{if(isDragging){isDragging=!1;widget.style.transition='';clearTimeout(dragTimeout);dragTimeout=setTimeout(()=>{hasDragged=!1},150)}});document.addEventListener('touchend',()=>{if(isDragging){isDragging=!1;widget.style.transition='';clearTimeout(dragTimeout);dragTimeout=setTimeout(()=>{hasDragged=!1},150)}});toggleBtn.addEventListener('click',function(e){if(hasDragged){hasDragged=!1;return}
toggleTranslateDropdown(e)})}
function toggleMobileMenu(){const menuToggle=document.getElementById('menu-toggle');const mobileMenu=document.getElementById('mobile-menu');if(!menuToggle||!mobileMenu)return;const isActive=mobileMenu.classList.contains('active');if(isActive){menuToggle.classList.remove('active');mobileMenu.classList.remove('active');menuToggle.setAttribute('aria-expanded','false');menuToggle.setAttribute('aria-label','Abrir menu');document.body.style.overflow=''}else{menuToggle.classList.add('active');mobileMenu.classList.add('active');menuToggle.setAttribute('aria-expanded','true');menuToggle.setAttribute('aria-label','Fechar menu')}}
function closeMobileMenu(){const menuToggle=document.getElementById('menu-toggle');const mobileMenu=document.getElementById('mobile-menu');if(!menuToggle||!mobileMenu)return;menuToggle.classList.remove('active');mobileMenu.classList.remove('active');menuToggle.setAttribute('aria-expanded','false');menuToggle.setAttribute('aria-label','Abrir menu');document.body.style.overflow=''}
function initMobileMenu(){const menuToggle=document.getElementById('menu-toggle');if(!menuToggle)return;menuToggle.addEventListener('click',(e)=>{e.stopPropagation();toggleMobileMenu()});document.addEventListener('click',(e)=>{const mobileMenu=document.getElementById('mobile-menu');if(!mobileMenu||!mobileMenu.classList.contains('active'))return;if(!mobileMenu.contains(e.target)&&e.target!==menuToggle){closeMobileMenu()}});window.addEventListener('resize',()=>{if(window.innerWidth>850)closeMobileMenu();})}
async function openPrivacyModal(){await loadModalContentVl('./politica-de-privacidade.html')}
async function openTermsModal(){await loadModalContentVl('./termos-de-uso.html')}
async function loadModalContentVl(filePath){const modal=document.getElementById('privacy-modal');const target=document.getElementById('privacy-content-target');if(modal&&target){modal.style.display='flex';modal.classList.add('active');document.body.style.overflow='hidden';target.innerHTML='<p>Carregando conteúdo...</p>';try{const response=await fetch(filePath);if(!response.ok)throw new Error('Arquivo não encontrado');target.innerHTML=await response.text();initSwipeToCloseVl()}catch(error){target.innerHTML=`
                <h2>Erro</h2>
                <p>Não foi possível carregar o conteúdo.</p>
                <p><a href="${filePath}" target="_blank" style="color: var(--primary-purple);">Clique aqui para abrir em uma nova aba.</a></p>
            `}}}
function closePrivacyModal(){const modal=document.getElementById('privacy-modal');if(modal){modal.classList.remove('active');setTimeout(()=>{if(!modal.classList.contains('active'))modal.style.display='none'},300);document.body.style.overflow=''}
const content=document.getElementById('privacy-modal-content');if(content){content.style.transform='';content.style.opacity=''}}
function initSwipeToCloseVl(){const modal=document.getElementById('privacy-modal');const content=document.getElementById('privacy-modal-content');if(!modal||!content)return;let startX=0,currentX=0,isDragging=!1;content.addEventListener('touchstart',(e)=>{startX=e.touches[0].clientX;isDragging=!0;content.style.transition='none'},{passive:!0});content.addEventListener('touchmove',(e)=>{if(!isDragging)return;currentX=e.touches[0].clientX;const diffX=currentX-startX;if(Math.abs(diffX)>20){content.style.transform=`translateX(${diffX}px)`;content.style.opacity=1-Math.abs(diffX)/400}},{passive:!0});content.addEventListener('touchend',()=>{if(!isDragging)return;isDragging=!1;const diffX=currentX-startX;content.style.transition='transform 0.3s ease, opacity 0.3s ease';if(Math.abs(diffX)>100){content.style.transform=diffX>0?'translateX(150%)':'translateX(-150%)';content.style.opacity='0';setTimeout(()=>{closePrivacyModal()},300)}else{content.style.transform='';content.style.opacity=''}
currentX=0})}
function closeToast(){const toast=document.getElementById('toast-container');if(toast){toast.classList.remove('show');document.body.style.overflow=''}}
function initBackToTopVl(){const backToTopButton=document.getElementById('back-to-top');if(backToTopButton){backToTopButton.style.display='none';window.addEventListener('scroll',function(){if(window.scrollY>300){backToTopButton.style.display='flex'}else{backToTopButton.style.display='none'}});backToTopButton.addEventListener('click',function(e){e.preventDefault();window.scrollTo({top:0,behavior:'smooth'})})}}
function initClickOutsideVl(){document.addEventListener('click',function(e){const translateDropdown=document.getElementById('translate-dropdown');const translateToggle=document.getElementById('translate-toggle');if(!translateDropdown||!translateToggle)return;if(!translateDropdown.contains(e.target)&&e.target!==translateToggle){setTimeout(()=>{translateDropdown.classList.remove('active')},150)}})}
function initEscapeKeyVl(){document.addEventListener('keydown',(e)=>{if(e.key==='Escape'){closePrivacyModal();closeMobileMenu();fecharModalVl();const translateDropdown=document.getElementById('translate-dropdown');if(translateDropdown)translateDropdown.classList.remove('active');}})}
function googleTranslateElementInit(){new google.translate.TranslateElement({pageLanguage:'pt',includedLanguages:'en,es,pt,it,fr,zh-CN,ja,hi',layout:google.translate.TranslateElement.InlineLayout.HORIZONTAL,autoDisplay:!1,multilanguagePage:!0,gaTrack:!1},'google_translate_element')}